name = "AdventOfCode"
uuid = "face5780-95c6-4d11-b8fa-be1c42eeb083"
authors = ["Frederik Schnack <frederik.schnack@ipp.mpg.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
